const os = require('os')

console.log(os.EOL)
console.log(os.EOL === '\n')
console.log(os.totalmem())
console.log(os.freemem())
console.log(os.type())
// console.log(os.UserInfo())
console.log(os.cpus())
console.log(os.homedir())